### 自定义异常

目前我们返回的一些异常信息，长这个样子

```python
{
    "detail": "Authentication credentials were not provided."
}
```

这样结构，对于移动端程序员是极其不友好的，所以我们一般给对方返回这样的数据结构

```python
{
    "code": 401,
    "message": "Authentication credentials were not provided.",
    "data": {}
}
```

那我们就需要自己异常来捕获DRF里面的异常信息

创建`custom_exception.py`文件

```python
from rest_framework.views import exception_handler


def custom_exception_handler(exc, context):
    response = exception_handler(exc, context)

    if response is not None:
        response.data['code'] = response.status_code
        response.data['message'] = response.data['detail']
        response.data['data'] = {}
        del response.data['detail']  # 删除detail字段

    return response

```

### 配置

```
'EXCEPTION_HANDLER': (
        'app06.custom_exception.custom_exception_handler'
)
```

